# This workflow will scrape and save covid vaccine availability data.

name: Scrape

on:
  schedule:
    - cron: '*/10 * * * *' # every ten minutes

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Scrape
      run: python scrape.py
    - uses: mikeal/publish-to-github-action@master
      env: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
