# This workflow will scrape and save covid vaccine availability data.

name: Scrape

on:
  pull_request:
    branches:
      - main
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Scrape
      run: python scrape.py
    - name: Commit files
      run: |
        git config --global user.email "bora.uyumazturk@gmail.com"
        git config --global user.name "Bora Uyumazturk"
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
        branch: main
